---
params:
  id_num: param_id_num
  name: param_name

---

# Pan param_id_num: param_name

```{r}
#| echo: false
#| message: false
#| warning: false
# annoyingly, we need to source our pre-render script for each chapter in the book
source("template/pre_render_script.R")
source("template/panning_pre_render.R")
```

```{r}
#| message: false
#| warning: false

# get enriched sequences
enriched_clustered <- determine_enriched(
    all_counts_filtered, params$id_num, logfc_cutoff = 1.5)

# create the pca plot & find top 100
cluster_pca_plot <- plot_cluster_pca(enriched_clustered, id = params$name)

# get full sequences
# first find the ones we are looking for (this pan, round 2 only)
wanted_samples <- metadata %>%
    filter(panning_id == params$id_num) %>%
    filter(round == 2) %>%
    pull(sample_num)

wanted_samples <- paste0(wanted_samples, "_")

all_files <- fs::dir_ls(glob = "*_nucleotide_sequences.tsv")
wanted_files <- str_subset(all_files, paste(wanted_samples, collapse = "|"))

nucleotide_sequences <- vroom(wanted_files)

# top 100 full sequences, with missing nt filled in
top_100_diversity_nt_seq <- get_full_sequences(
    cdr3s = cluster_pca_plot[["top_100_diversity"]],
    nucleotide_sequences,
    trim_5p = param_trim_5p, trim_3p = param_trim_3p)

top_100_enrichment_nt_seq <- get_full_sequences(
    cdr3s = cluster_pca_plot[["top_100_enrichment"]],
    nucleotide_sequences,
    trim_5p = param_trim_5p, trim_3p = param_trim_3p)

# write to file so they can be downloaded
Biostrings::writeXStringSet(
    top_100_diversity_nt_seq,
    file = paste0(
        str_replace_all(params$name, " ", "_"),
        "_top_100_diversity_nt_seq.fasta"))

Biostrings::writeXStringSet(
    top_100_enrichment_nt_seq,
    file = paste0(
        str_replace_all(params$name, " ", "_"),
        "_top_100_enrichment_nt_seq.fasta"))

# include the plot
cluster_pca_plot[["plot"]]
```

{{< downloadthis `r paste0(str_replace_all(params$name, " ", "_"), "_top_100_enrichment_nt_seq.fasta")` dname=`r paste0(str_replace_all(params$name, " ", "_"), "_top_100_enrichment_nt_seq")` label="Download top 100 (by enrichment) FASTA" icon=file-earmark-arrow-down type=secondary class=data-button id=top100_enrichment >}}

{{< downloadthis `r paste0(str_replace_all(params$name, " ", "_"), "_top_100_diversity_nt_seq.fasta")` dname=`r paste0(str_replace_all(params$name, " ", "_"), "_top_100_diversity_nt_seq")` label="Download top 100 (by diversity) FASTA" icon=file-earmark-arrow-down type=secondary class=data-button id=top100_diversity >}}